[build]
  ignore = "exit 0"
  command = "dotnet publish BlazorTipCalculator/BlazorTipCalculator.csproj -c Release -o publish"
  publish = "publish/wwwroot"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
